//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleLinqIntegration.RecordService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRecord", Namespace="http://schemas.datacontract.org/2004/07/RaisersEdge.API.ToolKit.Web.DataContracts" +
        "")]
    [System.SerializableAttribute()]
    public partial class BaseRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstituentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateLastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastChangedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MartialStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConstituentID {
            get {
                return this.ConstituentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstituentIDField, value) != true)) {
                    this.ConstituentIDField = value;
                    this.RaisePropertyChanged("ConstituentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateLastChanged {
            get {
                return this.DateLastChangedField;
            }
            set {
                if ((this.DateLastChangedField.Equals(value) != true)) {
                    this.DateLastChangedField = value;
                    this.RaisePropertyChanged("DateLastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastChangedBy {
            get {
                return this.LastChangedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastChangedByField, value) != true)) {
                    this.LastChangedByField = value;
                    this.RaisePropertyChanged("LastChangedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MartialStatus {
            get {
                return this.MartialStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MartialStatusField, value) != true)) {
                    this.MartialStatusField = value;
                    this.RaisePropertyChanged("MartialStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecordService.IRecordService")]
    public interface IRecordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordService/GetConstituent", ReplyAction="http://tempuri.org/IRecordService/GetConstituentResponse")]
        ExampleLinqIntegration.RecordService.BaseRecord GetConstituent(string constituentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecordService/UpdateConstituent", ReplyAction="http://tempuri.org/IRecordService/UpdateConstituentResponse")]
        bool UpdateConstituent(ExampleLinqIntegration.RecordService.BaseRecord updatedRecord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IRecordServiceChannel : ExampleLinqIntegration.RecordService.IRecordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RecordServiceClient : System.ServiceModel.ClientBase<ExampleLinqIntegration.RecordService.IRecordService>, ExampleLinqIntegration.RecordService.IRecordService {
        
        public RecordServiceClient() {
        }
        
        public RecordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExampleLinqIntegration.RecordService.BaseRecord GetConstituent(string constituentID) {
            return base.Channel.GetConstituent(constituentID);
        }
        
        public bool UpdateConstituent(ExampleLinqIntegration.RecordService.BaseRecord updatedRecord) {
            return base.Channel.UpdateConstituent(updatedRecord);
        }
    }
}
